version: '2'
services:
  michel-nginx:
    image: nginx
    container_name: michel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
#      - "/etc/nginx/vhost.d"
      - "/etc/nginx/passwords:/etc/nginx/htpasswd"
#      - "/usr/share/nginx/html"
#      - "/home/preprod/.zol/nginx/certs:/etc/nginx/certs:ro"
      - "~/.zol/nginx/certs:/etc/nginx/certs:ro"
      - "./conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
#      - "/srv/projects/fortrainjobs-front/fortrainjobs.conf:/etc/nginx/conf.d/fortrainjobs.conf:ro"
    networks:
      - nginx-proxy

  michel-dockergen:
    image: jwilder/docker-gen
    container_name: michel-dockergen
    command: -notify-sighup michel -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - michel-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - nginx-proxy

#  michel-letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: michel-letsencrypt
#    volumes_from:
#      - michel-nginx
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "/home/preprod/.zol/nginx/certs:/etc/nginx/certs:rw"
#    environment:
#      - NGINX_DOCKER_GEN_CONTAINER=michel-docker-gen

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
