version: '2'
services:
  michel-nginx:
    image: jwilder/nginx-proxy
    container_name: michel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
    networks:
      - nginx-proxy

  michel-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: michel-letsencrypt
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - nginx-proxy
#    environment:
#     - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
