version: '2'
services:
  michel-nginx:
    image: jwilder/nginx-proxy
    container_name: michel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf.d:/etc/nginx/conf.d"
      - "./vhost.d:/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
      - "./htpasswd:/etc/nginx/htpasswd"
      - "./certs:/etc/nginx/certs:ro"

    networks:
      - nginx-proxy

  michel-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: michel-letsencrypt
    volumes_from:
      - michel-nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/nginx_location.conf:/app/nginx_location.conf"
      - "./certs:/etc/nginx/certs:rw"
    networks:
      - nginx-proxy


  michel-fail2ban:
    build: ./docker/fail2ban
    restart: always
    container_name: michel-fail2ban
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/var/log/nginx"
    links:
      - michel-nginx


networks:
  nginx-proxy:
    external:
      name: nginx-proxy


